# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.cache/wt [current_project]
set_property parent.project_path E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty-z7-10:part0:1.1 [current_project]
set_property ip_output_repo e:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/sources_1/imports/tps_CLP/cont_ctl/fuentes/cont_ctl.vhd
  E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/sources_1/imports/tps_CLP/genEna/fuentes/genEna.vhd
  E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/sources_1/imports/tps_CLP/cont8b/fuentes/cont8b.vhd
  E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/sources_1/imports/tps_CLP/cont_top/fuentes/cont_top.vhd
  E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/sources_1/imports/tps_CLP/UART/fuentes/uart_rx.vhd
  E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/sources_1/imports/tps_CLP/UART/fuentes/meta_harden.vhd
  E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/sources_1/imports/tps_CLP/UART/fuentes/UART_cont.vhd
  E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/sources_1/imports/tps_CLP/UART/fuentes/UART_cont_top.vhd
  E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/sources_1/imports/tps_CLP/UART/fuentes/uart_baud_gen.vhd
  E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/sources_1/imports/tps_CLP/UART/fuentes/uart_rx_ctl.vhd
  {E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/sources_1/imports/fuentes/UART_cont_top _VIO.vhd}
}
read_ip -quiet E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/sources_1/ip/vio/vio.xci
set_property used_in_implementation false [get_files -all e:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/sources_1/ip/vio/vio.xdc]
set_property used_in_implementation false [get_files -all e:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/sources_1/ip/vio/vio_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/constrs_1/imports/fuentes/uart_led_pins_ArtyZ7.xdc
set_property used_in_implementation false [get_files E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/constrs_1/imports/fuentes/uart_led_pins_ArtyZ7.xdc]

read_xdc E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/constrs_1/imports/fuentes/uart_led_timing_ArtyZ7.xdc
set_property used_in_implementation false [get_files E:/Facultad/CLP/tps_CLP/UART_cont/UART_cont.srcs/constrs_1/imports/fuentes/uart_led_timing_ArtyZ7.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top UART_cont_top_VIO -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef UART_cont_top_VIO.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file UART_cont_top_VIO_utilization_synth.rpt -pb UART_cont_top_VIO_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
